version: "3.7"

services:
  mysql:
    restart: always
    image: mysql:8
    hostname: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: depscloud
    expose:
      - 3306

  tracker:
    restart: always
    image: depscloud/tracker:latest
    hostname: tracker
    depends_on:
      - mysql
    command:
      - --storage-driver=mysql
      - --storage-address=user:password@tcp(mysql:3306)/depscloud

  extractor:
    restart: always
    image: depscloud/extractor:latest
    hostname: extractor

  indexer:
    restart: on-failure
    image: depscloud/indexer:latest
    hostname: indexer
    depends_on:
      - extractor
      - tracker
    volumes:
      - ./rds.yaml:/etc/rds/config.yaml
    command:
      - --cron
      - --rds-config=/etc/rds/config.yaml
      - --workers=1

  gateway:
    restart: always
    image: depscloud/gateway:latest
    hostname: gateway
    depends_on:
      - extractor
      - tracker
    ports:
      - 8080:8080
